import streamlit as st
import pandas as pd
import json

# --- CONFIGURATION ---
# Use the same output files generated by main_sa.py or run_compare.py
SUMMARY_FILE = "run_summary.json" 
ASSIGNMENTS_FILE = "assignments.csv" 

# --- FUNCTIONS ---
@st.cache_data # Caching prevents reloading the files on every user interaction
def load_summary_data():
    """Load the JSON summary with overall metrics."""
    try:
        with open(SUMMARY_FILE, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        st.error(f"Error: {SUMMARY_FILE} not found. Run main_sa.py first.")
        return None

@st.cache_data
def load_assignments_data():
    """Load the detailed assignments CSV."""
    try:
        # We need to make sure the datetime columns are parsed correctly
        return pd.read_csv(ASSIGNMENTS_FILE, parse_dates=['start_time', 'finish_time'])
    except FileNotFoundError:
        return None
    
# --- STREAMLIT APP ---
st.title("AI Helpdesk Scheduling Results")

summary = load_summary_data()
assignments_df = load_assignments_data()

if summary is not None and assignments_df is not None:
    
    st.header(f"Scheduler: {summary['algorithm']['scheduler'].upper()}")
    st.caption(f"Tickets Processed: {summary['datasets']['n_tickets']} | Triage Method: {summary['algorithm']['triage']['method']}")
    
    # 1. Display Key Metrics using st.metric
    col1, col2, col3 = st.columns(3)
    
    metrics = summary['metrics_overall']
    
    col1.metric("SLA Breach Rate", f"{metrics['sla_breach_rate']:.2%}")
    col2.metric("Workload Variance", f"{metrics['workload_variance']:.2f}")
    col3.metric("Total Tardiness", f"{metrics['total_tardiness_minutes']} min")
    
    st.divider()

    # 2. Visualize Workload by Helper
    st.subheader("Helper Workload Distribution")
    
    # Use the loads_by_helper metric and convert to DataFrame for charting
    helper_load_data = pd.DataFrame(summary['metrics_by_helper'])
    helper_load_data = helper_load_data.set_index('helper_id')
    
    st.bar_chart(helper_load_data, y='tickets')
    

    st.divider()
    
    # 3. Display Interactive Assignment Table
    st.subheader("Full Assignment Schedule")
    
    # Drop irrelevant columns for cleaner display
    display_df = assignments_df.drop(columns=['customer_id', 'text', 'sla_hours', 'created_at'])
    
    if st.checkbox('Show raw data table'):
        # st.dataframe provides interactive filtering and sorting
        st.dataframe(display_df, use_container_width=True)